<?php
class Magazento_Sexybookmarks_Model_Source_Mode {

    public function toOptionArray() {
        return array(

            array('value' => 'shr-delicious', 'label' => Mage::helper('sexybookmarks')->__('delicious')),
            array('value' => 'shr-facebook', 'label' => Mage::helper('sexybookmarks')->__('facebook')),
            array('value' => 'shr-gmail', 'label' => Mage::helper('sexybookmarks')->__('gmail')),
            array('value' => 'shr-googlebuzz', 'label' => Mage::helper('sexybookmarks')->__('googlebuzz')),
            array('value' => 'shr-linkedin', 'label' => Mage::helper('sexybookmarks')->__('linkedin')),
            array('value' => 'shr-mail', 'label' => Mage::helper('sexybookmarks')->__('mail')),
            array('value' => 'shr-printfriendly', 'label' => Mage::helper('sexybookmarks')->__('printfriendly')),
            array('value' => 'shr-reddit', 'label' => Mage::helper('sexybookmarks')->__('reddit')),
            array('value' => 'shr-stumbleupon', 'label' => Mage::helper('sexybookmarks')->__('stumbleupon')),
            array('value' => 'shr-twitter', 'label' => Mage::helper('sexybookmarks')->__('twitter')),
            array('value' => 'shr-100zakladok', 'label' => Mage::helper('sexybookmarks')->__('100zakladok')),
            array('value' => 'shr-bebo', 'label' => Mage::helper('sexybookmarks')->__('bebo')),
            array('value' => 'shr-bitacoras', 'label' => Mage::helper('sexybookmarks')->__('bitacoras')),
            array('value' => 'shr-blinklist', 'label' => Mage::helper('sexybookmarks')->__('blinklist')),
            array('value' => 'shr-blogengage', 'label' => Mage::helper('sexybookmarks')->__('blogengage')),
            array('value' => 'shr-blogger', 'label' => Mage::helper('sexybookmarks')->__('blogger')),
            array('value' => 'shr-blogmarks', 'label' => Mage::helper('sexybookmarks')->__('blogmarks')),
            array('value' => 'shr-bobrdobr', 'label' => Mage::helper('sexybookmarks')->__('bobrdobr')),
            array('value' => 'shr-bonzobox', 'label' => Mage::helper('sexybookmarks')->__('bonzobox')),
            array('value' => 'shr-box', 'label' => Mage::helper('sexybookmarks')->__('box')),
            array('value' => 'shr-buzzster', 'label' => Mage::helper('sexybookmarks')->__('buzzster')),
//            array('value' => 'shr-comfeed', 'label' => Mage::helper('sexybookmarks')->__('comfeed')),
            array('value' => 'shr-current', 'label' => Mage::helper('sexybookmarks')->__('current')),
            array('value' => 'shr-designbump', 'label' => Mage::helper('sexybookmarks')->__('designbump')),
            array('value' => 'shr-designfloat', 'label' => Mage::helper('sexybookmarks')->__('designfloat')),
            array('value' => 'shr-digg', 'label' => Mage::helper('sexybookmarks')->__('digg')),
            array('value' => 'shr-diigo', 'label' => Mage::helper('sexybookmarks')->__('diigo')),
            array('value' => 'shr-dzone', 'label' => Mage::helper('sexybookmarks')->__('dzone')),
            array('value' => 'shr-ekudos', 'label' => Mage::helper('sexybookmarks')->__('ekudos')),
            array('value' => 'shr-evernote', 'label' => Mage::helper('sexybookmarks')->__('evernote')),
            array('value' => 'shr-faqpal', 'label' => Mage::helper('sexybookmarks')->__('faqpal')),
            array('value' => 'shr-friendfeed', 'label' => Mage::helper('sexybookmarks')->__('friendfeed')),
            array('value' => 'shr-fwisp', 'label' => Mage::helper('sexybookmarks')->__('fwisp')),
            array('value' => 'shr-globalgrind', 'label' => Mage::helper('sexybookmarks')->__('globalgrind')),
            array('value' => 'shr-googlebookmarks', 'label' => Mage::helper('sexybookmarks')->__('googlebookmarks')),
            array('value' => 'shr-googlereader', 'label' => Mage::helper('sexybookmarks')->__('googlereader')),
            array('value' => 'shr-hackernews', 'label' => Mage::helper('sexybookmarks')->__('hackernews')),
            array('value' => 'shr-hatena', 'label' => Mage::helper('sexybookmarks')->__('hatena')),
            array('value' => 'shr-hotmail', 'label' => Mage::helper('sexybookmarks')->__('hotmail')),
            array('value' => 'shr-hyves', 'label' => Mage::helper('sexybookmarks')->__('hyves')),
            array('value' => 'shr-identica', 'label' => Mage::helper('sexybookmarks')->__('identica')),
            array('value' => 'shr-izeby', 'label' => Mage::helper('sexybookmarks')->__('izeby')),
            array('value' => 'shr-jumptags', 'label' => Mage::helper('sexybookmarks')->__('jumptags')),
            array('value' => 'shr-kaevur', 'label' => Mage::helper('sexybookmarks')->__('kaevur')),
            array('value' => 'shr-memoryru', 'label' => Mage::helper('sexybookmarks')->__('memoryru')),
            array('value' => 'shr-meneame', 'label' => Mage::helper('sexybookmarks')->__('meneame')),
            array('value' => 'shr-misterwong', 'label' => Mage::helper('sexybookmarks')->__('misterwong')),
            array('value' => 'shr-mixx', 'label' => Mage::helper('sexybookmarks')->__('mixx')),
            array('value' => 'shr-moemesto', 'label' => Mage::helper('sexybookmarks')->__('moemesto')),
            array('value' => 'shr-mylinkvault', 'label' => Mage::helper('sexybookmarks')->__('mylinkvault')),
            array('value' => 'shr-myspace', 'label' => Mage::helper('sexybookmarks')->__('myspace')),
            array('value' => 'shr-n4g', 'label' => Mage::helper('sexybookmarks')->__('n4g')),
            array('value' => 'shr-netvibes', 'label' => Mage::helper('sexybookmarks')->__('netvibes')),
            array('value' => 'shr-netvouz', 'label' => Mage::helper('sexybookmarks')->__('netvouz')),
            array('value' => 'shr-newsvine', 'label' => Mage::helper('sexybookmarks')->__('newsvine')),
            array('value' => 'shr-ning', 'label' => Mage::helper('sexybookmarks')->__('ning')),
            array('value' => 'shr-nujij', 'label' => Mage::helper('sexybookmarks')->__('nujij')),
            array('value' => 'shr-oknotizie', 'label' => Mage::helper('sexybookmarks')->__('oknotizie')),
            array('value' => 'shr-orkut', 'label' => Mage::helper('sexybookmarks')->__('orkut')),
            array('value' => 'shr-pfbuzz', 'label' => Mage::helper('sexybookmarks')->__('pfbuzz')),
            array('value' => 'shr-pingfm', 'label' => Mage::helper('sexybookmarks')->__('pingfm')),
            array('value' => 'shr-plaxo', 'label' => Mage::helper('sexybookmarks')->__('plaxo')),
            array('value' => 'shr-plurk', 'label' => Mage::helper('sexybookmarks')->__('plurk')),
            array('value' => 'shr-posterous', 'label' => Mage::helper('sexybookmarks')->__('posterous')),
            array('value' => 'shr-propeller', 'label' => Mage::helper('sexybookmarks')->__('propeller')),
            array('value' => 'shr-pusha', 'label' => Mage::helper('sexybookmarks')->__('pusha')),
            array('value' => 'shr-scriptstyle', 'label' => Mage::helper('sexybookmarks')->__('scriptstyle')),
            array('value' => 'shr-slashdot', 'label' => Mage::helper('sexybookmarks')->__('slashdot')),
            array('value' => 'shr-sphinn', 'label' => Mage::helper('sexybookmarks')->__('sphinn')),
            array('value' => 'shr-springpad', 'label' => Mage::helper('sexybookmarks')->__('springpad')),
            array('value' => 'shr-squidoo', 'label' => Mage::helper('sexybookmarks')->__('squidoo')),
            array('value' => 'shr-strands', 'label' => Mage::helper('sexybookmarks')->__('strands')),
            array('value' => 'shr-stumpedia', 'label' => Mage::helper('sexybookmarks')->__('techmeme')),
            array('value' => 'shr-techmeme', 'label' => Mage::helper('sexybookmarks')->__('techmeme')),
            array('value' => 'shr-technorati', 'label' => Mage::helper('sexybookmarks')->__('tipd')),
            array('value' => 'shr-tipd', 'label' => Mage::helper('sexybookmarks')->__('technorati')),
            array('value' => 'shr-tomuse', 'label' => Mage::helper('sexybookmarks')->__('tomuse')),
            array('value' => 'shr-tumblr', 'label' => Mage::helper('sexybookmarks')->__('tumblr')),
            array('value' => 'shr-twittley', 'label' => Mage::helper('sexybookmarks')->__('twittley')),
            array('value' => 'shr-viadeo', 'label' => Mage::helper('sexybookmarks')->__('viadeo')),
            array('value' => 'shr-virb', 'label' => Mage::helper('sexybookmarks')->__('virb')),
            array('value' => 'shr-webblend', 'label' => Mage::helper('sexybookmarks')->__('webblend')),
            array('value' => 'shr-wykop', 'label' => Mage::helper('sexybookmarks')->__('wykop')),
            array('value' => 'shr-xerpi', 'label' => Mage::helper('sexybookmarks')->__('xerpi')),
            array('value' => 'shr-yahoobuzz', 'label' => Mage::helper('sexybookmarks')->__('yahoobuzz')),
            array('value' => 'shr-yahoomail', 'label' => Mage::helper('sexybookmarks')->__('yahoomail')),
            array('value' => 'shr-yandex', 'label' => Mage::helper('sexybookmarks')->__('yandex')),
            array('value' => 'shr-zabox', 'label' => Mage::helper('sexybookmarks')->__('zabox'))


        );
    }

}