<?php
if (Mage::helper('sexybookmarks')->isBookmarksEnabled()) {
    $page_title=$this->getLayout()->getBlock('head')->getTitle();
    $page_url=Mage::helper('core/url')->getCurrentUrl();
?>


    <script src="<?php echo $this->getSkinUrl('magazento/sexybookmarks/jquery.js') ?>" type="text/javascript"></script>
    <link rel="stylesheet" href="<?php echo $this->getSkinUrl('magazento/sexybookmarks/shr-custom-sprite.css') ?>" type="text/css" media="screen" />
    <script src="<?php echo $this->getSkinUrl('magazento/sexybookmarks/sexy-bookmarks-public.js') ?>" type="text/javascript"></script>

    <div class="sexymagentobookmarks-container">
        <div class="shr-bookmarks-bg-caring">
            <div class="shr-bookmarks shr-bookmarks-expand shr-bookmarks-center" style="margin-left: 15px ! important; height: 32px; display: block; overflow: hidden;">
                <ul class="socials">

                   <?php echo Mage::helper('sexybookmarks')->printBookmarks($page_title,$page_url); ?>
                </ul>
            </div>    
        </div>
    </div>


<?php } ?>













<!--echo Mage::getModel('sexybookmarks/list')->getList();-->